@startuml
actor actor
agent agent
artifact artifact
boundary boundary
card card
circle circle
cloud cloud
collections collections
component component
control control
database database
entity entity
file file
folder folder
frame frame
interface interface
node node
package package
queue queue
rectangle rectangle
stack stack
storage storage
usecase usecase
/' hexagon hexagon '/
/' label label '/
/' person person '/
@enduml
