@startuml
skinparam titleFontSize 14

title
  Fieldset
  |_ **Screen**
    |_ **Group**
      |_ **Field**{label=<color:green>"Listing title"</color>, component=<color:green>"text_input"</color>}
      |_ **Field**{label=<color:green>"Category"</color>, component=<color:green>"category_picker"</color>}
      |_ **Field**{label=<color:green>"Photo"</color>, component=<color:green>"photo_picker"</color>}
    |_ **Group**{title=<color:green>"About the item"</color>}
      |_ **Field**{label=<color:green>"Condition"</color>, component=<color:green>"single_picker"</color>}
      |_ **Field**{label=<color:green>"Price"</color>, component=<color:green>"single_picker"</color>}
      |_ **Field**{label=<color:green>""</color>, component=<color:green>"numeric_input"</color>}
      |_ **Field**{label=<color:green>"Description"</color>, component=<color:green>"text_input"</color>}
      |_ **Field**{label=<color:green>"Brand"</color>, component=<color:green>"single_picker"</color>}
      |_ **Field**{label=<color:green>"Size"</color>, component=<color:green>"single_picker"</color>}
    |_ **Group**{title=<color:green>"Optional details"</color>}
      |_ **Field**{label=<color:green>"Colour"</color>, component=<color:green>"single_picker"</color>}
      |_ **Field**{label=<color:green>"Chest"</color>, component=<color:green>"numeric_input"</color>}
      |_ **Field**{label=<color:green>"Length"</color>, component=<color:green>"numeric_input"</color>}
      |_ **Field**{label=<color:green>"Multiple quantities"</color>, component=<color:green>"checkbox"</color>}
end title

@enduml
