baseURL = "https://kb.hbenjamin.com/"
languageCode = "en-us"
title = "Knowledge Base"
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
enableEmoji = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        style = "lovelace"
    [markup.goldmark.renderer]
        unsafe = true
