[context.production.environment]
HUGO_VERSION = "0.83.0"

[context.deploy-preview]
command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.83.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.83.0"
